=== mesrarmahmoud/projet_xml_webService/Partie_A/ReleverDTD.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT relever (dateRelever,solde,operations+) >
<!ELEMENT operations (operation+) >
<!ELEMENT dateRelever ANY >
<!ELEMENT solde ANY >
<!ELEMENT  operation EMPTY >

<!ATTLIST relever 
    RIB NMTOKEN #REQUIRED>
    
<!ATTLIST operations  
    dateDebut CDATA #REQUIRED
    dateFin CDATA #REQUIRED>
    
<!ATTLIST operation 
        type (CREDIT|DEBIT) "DEBIT"
        date CDATA #REQUIRED
        montant NMTOKEN #REQUIRED
        description CDATA #IMPLIED
    >

=== mesrarmahmoud/projet_xml_webService/A/releverDTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE relever SYSTEM "ReleverDTD.dtd">
<?xml-stylesheet type="text/xsl" href="relever1.xsl"?>
<relever RIB="2345566443322345">
    <dateRelever>2021-11-10</dateRelever>
    <solde>14500</solde>
    <operations dateDebut="2021-01-01" dateFin="2021-01-30">
        <operation type="CREDIT" date="2021-01-11" montant="9000" description="Virement espece" />
        <operation type="DEBIT" date="2021-01-11" montant="3400" description="cheque gichet" />
        <operation type="DEBIT" date="2021-01-11" montant="2000" description="PrÃ©levement assurence"/>
        <operation type="CREDIT" date="2021-01-11" montant="1000" description="Virement.."/>
    </operations>
</relever>
